[package]
name = "rotopong"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
impacted = { version = "1.4.0", features = ["bevy-07"] }
bevy_egui = "0.13"
